spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri : ?????
          ignore-local-ssh-settings: true
          private-key: |
            -----BEGIN RSA PRIVATE KEY-----
            
            -----END RSA PRIVATE KEY-----

server:
  port: 20000


